# Generated by Django 5.0.3 on 2025-06-30 09:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alarmmodel',
            name='uid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='batterytype',
            name='uid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='uid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
    ]
