# Generated by Django 5.0.3 on 2025-06-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_manufacturer_is_active_alter_alarmmodel_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='alarmmodel',
            name='is_hardwired',
            field=models.BooleanField(default=False, verbose_name='Hardwired'),
        ),
        migrations.AlterField(
            model_name='alarmmodel',
            name='is_wireless',
            field=models.BooleanField(default=False, verbose_name='Wireless'),
        ),
    ]
