# Generated by Django 5.2.3 on 2025-06-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('street_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Street Number')),
                ('street_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Name')),
                ('suburb', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal/Zip Code')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('who_contacted', models.CharField(max_length=255)),
                ('contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('work_order', 'Work Order')], max_length=10)),
                ('work_order_number', models.CharField(blank=True, max_length=255)),
                ('sound_type', models.CharField(max_length=50)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('brand', models.CharField(max_length=100)),
                ('hardware', models.IntegerField(blank=True, null=True)),
                ('wireless', models.IntegerField(blank=True, null=True)),
                ('tenant_names', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('stage', models.CharField(choices=[('to_be_booked', 'To Be Booked'), ('quote_sent', 'Quote Sent'), ('completed', 'Completed'), ('to_be_called', 'To Be Called')], default='to_be_booked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
