# Generated by Django 5.2.3 on 2025-06-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='is_rental_private',
            field=models.BooleanField(default=False),
        ),
    ]
