# Generated by Django 5.2.3 on 2025-06-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0002_alarm_is_rental_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='realestate_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
