# Generated by Django 5.2.3 on 2025-06-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0003_alarm_realestate_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarm',
            old_name='is_rental_private',
            new_name='is_private',
        ),
        migrations.AddField(
            model_name='alarm',
            name='is_rental',
            field=models.BooleanField(default=False),
        ),
    ]
