# Generated by Django 5.2.3 on 2025-06-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0005_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='tenant_names',
        ),
    ]
