# Generated by Django 5.2.3 on 2025-06-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0006_remove_alarm_phone_remove_alarm_tenant_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarm',
            old_name='hardware',
            new_name='hardwire_alarm',
        ),
        migrations.RenameField(
            model_name='alarm',
            old_name='wireless',
            new_name='wireless_alarm',
        ),
        migrations.AddField(
            model_name='alarm',
            name='is_wall_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='brand',
            field=models.CharField(choices=[('red', 'Red'), ('firepro', 'FirePro'), ('emerald', 'Emerald'), ('cavius', 'Cavius'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='sound_type',
            field=models.CharField(choices=[('full_alarm', 'Full Alarm'), ('chirping_alarm', 'Chirping Alarm')], max_length=50),
        ),
    ]
