# Generated by Django 5.2.3 on 2025-06-21 10:38

import alarms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0009_alarmimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmimage',
            name='image',
            field=models.ImageField(upload_to=alarms.models.alarm_image_path),
        ),
    ]
