# Generated by Django 5.0.3 on 2025-06-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0010_alter_alarmimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmimage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
