# Generated by Django 5.0.3 on 2025-06-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0011_alter_alarmimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='notes',
            field=models.TextField(blank=True, help_text='Initial notes for the alarm', null=True),
        ),
    ]
