# Generated by Django 5.2.3 on 2025-07-01 04:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0014_alter_property_agency_alter_property_private_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeepingAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('requires_call_back', 'Requires Call Back'), ('awaiting_response', 'Awaiting Response'), ('to_be_scheduled', 'To Be Scheduled'), ('to_be_quoted', 'To Be Quoted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=100)),
                ('notes', models.TextField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('is_agency', models.BooleanField(default=True)),
                ('is_private_owner', models.BooleanField(default=True)),
                ('is_customer_contacted', models.BooleanField(default=False, verbose_name='Customer Contacted')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.agency')),
                ('allocation', models.ManyToManyField(related_name='alarm_issues', to=settings.AUTH_USER_MODEL)),
                ('private_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.privateowner')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.tenant')),
                ('issue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.issuetype')),
            ],
        ),
        migrations.CreateModel(
            name='BeepingAlarmUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('requires_call_back', 'Requires Call Back'), ('awaiting_response', 'Awaiting Response'), ('to_be_scheduled', 'To Be Scheduled'), ('to_be_quoted', 'To Be Quoted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(max_length=1000)),
                ('beeping_alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.beepingalarm')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
