# Generated by Django 5.0.3 on 2025-06-30 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Alarmissue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('requires_call_back', 'Requires Call Back'), ('awaiting_response', 'Awaiting Response'), ('to_be_scheduled', 'To Be Scheduled'), ('to_be_quoted', 'To Be Quoted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=100)),
                ('notes', models.TextField(max_length=1000)),
                ('allocation', models.ManyToManyField(related_name='alarm_issues', to=settings.AUTH_USER_MODEL)),
                ('issue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.issuetype')),
            ],
        ),
    ]
