# Generated by Django 5.2.3 on 2025-07-01 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('properties', '0014_alter_property_agency_alter_property_private_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beepingalarm',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.agency'),
        ),
        migrations.AlterField(
            model_name='beepingalarm',
            name='private_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.privateowner'),
        ),
    ]
