# Generated by Django 5.0.3 on 2025-06-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetype',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
