# Generated by Django 5.2.3 on 2025-07-01 05:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_beepingalarm_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beepingalarm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beepingalarm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]