# Generated by Django 5.0.3 on 2025-06-30 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_issuetype_description'),
        ('properties', '0004_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmissue',
            name='agency',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='properties.agency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alarmissue',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alarmissue',
            name='is_agency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarmissue',
            name='is_private_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarmissue',
            name='private_owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='properties.privateowner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alarmissue',
            name='property',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
            preserve_default=False,
        ),
    ]
