# Generated by Django 5.2.3 on 2025-07-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_beepingalarm_created_at_beepingalarm_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='beepingalarm',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
