# Generated by Django 5.0.3 on 2025-06-30 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alarmissue_agency_alarmissue_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuetype',
            name='uid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='alarmissue',
            name='uid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
    ]
