# Generated by Django 5.2.3 on 2025-07-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_beepingalarm_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='beepingalarm',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
