# Generated by Django 5.0.3 on 2025-06-30 10:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_issuetype_uid_alter_alarmissue_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmIssueUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('requires_call_back', 'Requires Call Back'), ('awaiting_response', 'Awaiting Response'), ('to_be_scheduled', 'To Be Scheduled'), ('to_be_quoted', 'To Be Quoted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(max_length=1000)),
                ('alarm_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.alarmissue')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
