# Generated by Django 5.0.3 on 2025-06-30 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alarmissueupdate'),
        ('properties', '0014_alter_property_agency_alter_property_private_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmissue',
            name='is_customer_contacted',
            field=models.BooleanField(default=False, verbose_name='Customer Contacted'),
        ),
        migrations.AddField(
            model_name='alarmissue',
            name='tenant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='properties.tenant'),
            preserve_default=False,
        ),
    ]
