# Generated by Django 5.2.3 on 2025-07-04 04:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_beepingalarm_is_cancelled'),
        ('properties', '0014_alter_property_agency_alter_property_private_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='beepingalarm',
            name='allocation',
            field=models.ManyToManyField(blank=True, related_name='alarm_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='beepingalarm',
            name='tenant',
        ),
        migrations.AddField(
            model_name='beepingalarm',
            name='tenant',
            field=models.ManyToManyField(blank=True, related_name='alarm_issues', to='properties.tenant'),
        ),
    ]
