# Generated by Django 5.2.3 on 2025-07-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_alter_beepingalarm_allocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beepingalarm',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
