# Generated by Django 5.0.3 on 2025-07-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_alter_beepingalarm_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
