# Generated by Django 5.0.3 on 2025-07-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_issuetype_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beepingalarm',
            name='tenant',
        ),
    ]
