# Generated by Django 5.0.3 on 2025-07-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_remove_beepingalarm_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beepingalarm',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='beepingalarm',
            name='is_agency',
        ),
        migrations.RemoveField(
            model_name='beepingalarm',
            name='is_private_owner',
        ),
        migrations.RemoveField(
            model_name='beepingalarm',
            name='private_owner',
        ),
    ]
