# Generated by Django 5.2.3 on 2025-07-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_remove_beepingalarm_agency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beepingalarmupdate',
            old_name='date',
            new_name='created_at',
        ),
    ]
