# Generated by Django 5.2.3 on 2025-07-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_rename_date_beepingalarmupdate_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beepingalarm',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('requires_call_back', 'Requires Call Back'), ('awaiting_response', 'Awaiting Response'), ('to_be_scheduled', 'To Be Scheduled'), ('to_be_quoted', 'To Be Quoted'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('update', 'Update')], default='new', max_length=100),
        ),
        migrations.AlterField(
            model_name='beepingalarmupdate',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('requires_call_back', 'Requires Call Back'), ('awaiting_response', 'Awaiting Response'), ('to_be_scheduled', 'To Be Scheduled'), ('to_be_quoted', 'To Be Quoted'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('update', 'Update')], max_length=100),
        ),
    ]
