# Generated by Django 5.0.3 on 2025-06-30 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('notes', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='agency',
            old_name='address',
            new_name='street_name',
        ),
        migrations.AddField(
            model_name='agency',
            name='street_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='unit_number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=100, unique=True)),
                ('unit_number', models.CharField(max_length=100)),
                ('street_number', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=100)),
                ('suburb', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.agency')),
                ('private_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.privateowner')),
            ],
        ),
    ]
