# Generated by Django 5.0.3 on 2025-06-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_privateowner_rename_address_agency_street_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='UID',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='privateowner',
            old_name='UID',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='UID',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='propertymanager',
            old_name='UID',
            new_name='uid',
        ),
    ]
