# Generated by Django 5.0.3 on 2025-06-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_agency_country_alter_agency_postcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateowner',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='privateowner',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
