# Generated by Django 5.0.3 on 2025-06-30 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_privateowner_email_alter_privateowner_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanager',
            name='agency',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='properties.agency'),
            preserve_default=False,
        ),
    ]
