# Generated by Django 5.0.3 on 2025-06-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_propertymanager_agency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privateowner',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='propertymanager',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='privateowner',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
