# Generated by Django 5.0.3 on 2025-06-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_rename_name_privateowner_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanager',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
