# Generated by Django 5.0.3 on 2025-06-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_propertymanager_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='unit_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
