# Generated by Django 5.0.3 on 2025-06-30 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_agency_latitude_agency_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.agency'),
        ),
        migrations.AlterField(
            model_name='property',
            name='private_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.privateowner'),
        ),
    ]
