# Generated by Django 5.0.3 on 2025-07-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_alter_property_agency_alter_property_private_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='tenants',
            field=models.ManyToManyField(blank=True, related_name='properties', to='properties.tenant'),
        ),
    ]
