# Generated by Django 5.2.3 on 2025-07-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_property_tenants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymanager',
            name='agency',
        ),
        migrations.AddField(
            model_name='agency',
            name='property_managers',
            field=models.ManyToManyField(blank=True, related_name='agencies', to='properties.propertymanager'),
        ),
    ]
