# Generated by Django 5.2.3 on 2025-07-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_remove_propertymanager_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateowner',
            name='property_managers',
            field=models.ManyToManyField(blank=True, related_name='private_owners', to='properties.propertymanager'),
        ),
    ]
