# Generated by Django 5.2.3 on 2025-07-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_privateowner_property_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateowner',
            name='property_managers',
        ),
        migrations.RemoveField(
            model_name='property',
            name='private_owner',
        ),
        migrations.AddField(
            model_name='property',
            name='private_owners',
            field=models.ManyToManyField(blank=True, related_name='properties', to='properties.privateowner'),
        ),
    ]
