# Generated by Django 5.2.3 on 2025-07-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_remove_privateowner_property_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_agency',
            field=models.BooleanField(default=False, help_text='True if property is managed by an agency'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_private',
            field=models.BooleanField(default=False, help_text='True if property is managed by private owners'),
        ),
    ]
