# Generated by Django 5.2.3 on 2025-07-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_property_is_agency_property_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
