# Generated by Django 5.2.3 on 2025-07-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_agency_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateowner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
